library:
  source-dirs: src
tests:
  ConwayLife-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ConwayLife
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- ansi-terminal
- extra
- containers
- base >= 4.7 && < 5
name: ConwayLife
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/ConwayLife
license: BSD3
executables:
  ConwayLife-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ConwayLife
description: Please see the README on GitHub at <https://github.com/githubuser/ConwayLife#readme>
